<?php

$permissions = [
    'dashboard.view' => 'Xem bảng điều khiển',
    'cars.view' => 'Xem xe',
    'cars.create' => 'Tạo xe',
    'cars.edit' => 'Sửa xe',
    'cars.delete' => 'Xóa xe',
    'inventory.view' => 'Xem tồn kho',
    'inventory.adjust' => 'Điều chỉnh tồn kho',
    'inventory.history' => 'Xem lịch sử tồn kho',
    'customers.view' => 'Xem khách hàng',
    'customers.create' => 'Tạo khách hàng',
    'customers.edit' => 'Sửa khách hàng',
    'customers.delete' => 'Xóa khách hàng',
    'orders.view' => 'Xem đơn hàng',
    'orders.create' => 'Tạo đơn hàng',
    'orders.edit' => 'Sửa đơn hàng',
    'quotes.view' => 'Xem báo giá',
    'quotes.create' => 'Tạo báo giá',
    'quotes.edit' => 'Sửa báo giá',
    'quotes.delete' => 'Xóa báo giá',
    'news.view' => 'Xem tin tức',
    'news.create' => 'Tạo tin tức',
    'news.edit' => 'Sửa tin tức',
    'news.delete' => 'Xóa tin tức',
    'news.publish' => 'Xuất bản tin tức',
    'news_categories.view' => 'Xem chuyên mục tin tức',
    'news_categories.create' => 'Tạo chuyên mục tin tức',
    'news_categories.edit' => 'Sửa chuyên mục tin tức',
    'news_categories.delete' => 'Xóa chuyên mục tin tức',
    'promotions.view' => 'Xem khuyến mãi',
    'promotions.create' => 'Tạo khuyến mãi',
    'promotions.edit' => 'Sửa khuyến mãi',
    'promotions.delete' => 'Xóa khuyến mãi',
    'promotions.publish' => 'Xuất bản khuyến mãi',
    'promotions.apply' => 'Áp dụng khuyến mãi vào báo giá',
    'reports.view' => 'Xem báo cáo',
    'users.view' => 'Xem người dùng',
    'users.create' => 'Tạo người dùng',
    'users.edit' => 'Sửa người dùng',
    'users.delete' => 'Xóa người dùng',
    'roles.view' => 'Xem vai trò',
    'roles.create' => 'Tạo vai trò',
    'roles.edit' => 'Sửa vai trò',
    'roles.delete' => 'Xóa vai trò',
    'reviews.view' => 'Xem đánh giá',
    'reviews.moderate' => 'Duyệt và ẩn đánh giá',
    'reviews.reply' => 'Phản hồi đánh giá',
    'reviews.delete' => 'Xóa đánh giá',
    'reviews.export' => 'Xuất Excel đánh giá',
    'live.view' => 'Xem livestream',
    'live.create' => 'Tạo phiên livestream',
    'live.edit' => 'Cập nhật livestream',
    'live.delete' => 'Xóa phiên livestream',
    'live.manage' => 'Bật tắt và kết thúc livestream',
    'live.leads.view' => 'Xem live lead',
    'live.leads.edit' => 'Cập nhật live lead',
    'live.reports.view' => 'Xem báo cáo livestream',
    'tickets.view' => 'Xem hỗ trợ',
    'tickets.reply' => 'Trả lời hỗ trợ',
    'warranties.view' => 'Xem bảo hành',
    'warranties.create' => 'Tạo bảo hành',
    'warranties.edit' => 'Sửa bảo hành',
    'warranties.delete' => 'Xóa bảo hành',
    'services.view' => 'Xem lịch dịch vụ',
    'services.create' => 'Tạo lịch dịch vụ',
    'services.edit' => 'Sửa lịch dịch vụ',
    'services.delete' => 'Xóa lịch dịch vụ',
    'service_records.view' => 'Xem lịch sử dịch vụ',
    'service_records.create' => 'Tạo lịch sử dịch vụ',
    'service_records.edit' => 'Sửa lịch sử dịch vụ',
    'service_records.delete' => 'Xóa lịch sử dịch vụ',
    'test_drives.view' => 'Xem lịch lái thử',
    'test_drives.edit' => 'Cập nhật lịch lái thử',
    'test_drives.delete' => 'Xóa tài liệu lái thử',
    'test_drives.export' => 'Xuất Excel lịch lái thử',
];

$allPermissions = array_keys($permissions);

return [
    'guard' => 'web',

    'permissions' => $permissions,

    'groups' => [
        'dashboard' => [
            'label' => 'Bảng điều khiển',
            'permissions' => ['dashboard.view'],
        ],
        'cars' => [
            'label' => 'Xe',
            'permissions' => ['cars.view', 'cars.create', 'cars.edit', 'cars.delete'],
        ],
        'inventory' => [
            'label' => 'Tồn kho',
            'permissions' => ['inventory.view', 'inventory.adjust', 'inventory.history'],
        ],
        'sales' => [
            'label' => 'Bán hàng',
            'permissions' => [
                'customers.view',
                'customers.create',
                'customers.edit',
                'customers.delete',
                'orders.view',
                'orders.create',
                'orders.edit',
                'quotes.view',
                'quotes.create',
                'quotes.edit',
                'quotes.delete',
                'promotions.apply',
                'reviews.view',
                'test_drives.view',
                'test_drives.edit',
                'test_drives.delete',
                'test_drives.export',
                'live.leads.view',
                'live.leads.edit',
            ],
        ],
        'marketing' => [
            'label' => 'Marketing',
            'permissions' => [
                'news.view',
                'news.create',
                'news.edit',
                'news.delete',
                'news.publish',
                'news_categories.view',
                'news_categories.create',
                'news_categories.edit',
                'news_categories.delete',
                'promotions.view',
                'promotions.create',
                'promotions.edit',
                'promotions.delete',
                'promotions.publish',
                'promotions.apply',
                'reviews.view',
                'reviews.moderate',
                'reviews.reply',
                'reviews.delete',
                'reviews.export',
                'live.view',
                'live.create',
                'live.edit',
                'live.manage',
                'live.leads.view',
            ],
        ],
        'support' => [
            'label' => 'Hỗ trợ',
            'permissions' => [
                'tickets.view',
                'tickets.reply',
                'warranties.view',
                'warranties.create',
                'warranties.edit',
                'warranties.delete',
                'services.view',
                'services.create',
                'services.edit',
                'services.delete',
                'service_records.view',
                'service_records.create',
                'service_records.edit',
                'service_records.delete',
                'reviews.view',
                'reviews.moderate',
                'reviews.reply',
            ],
        ],
        'reports' => [
            'label' => 'Báo cáo',
            'permissions' => ['reports.view', 'live.reports.view'],
        ],
        'system' => [
            'label' => 'Hệ thống',
            'permissions' => [
                'users.view',
                'users.create',
                'users.edit',
                'users.delete',
                'roles.view',
                'roles.create',
                'roles.edit',
                'roles.delete',
            ],
        ],
    ],

    'roles' => [
        'Super Admin' => [
            'legacy_role' => 'admin',
            'permissions' => '*',
        ],
        'Admin' => [
            'legacy_role' => 'admin',
            'permissions' => array_values(array_diff($allPermissions, ['roles.delete'])),
        ],
        'Quản lý kho' => [
            'legacy_role' => 'staff',
            'permissions' => [
                'dashboard.view',
                'cars.view',
                'inventory.view',
                'inventory.adjust',
                'inventory.history',
            ],
        ],
        'Nhân viên bán hàng' => [
            'legacy_role' => 'staff',
            'permissions' => [
                'dashboard.view',
                'cars.view',
                'customers.view',
                'customers.create',
                'customers.edit',
                'customers.delete',
                'orders.view',
                'orders.create',
                'orders.edit',
                'quotes.view',
                'quotes.create',
                'quotes.edit',
                'quotes.delete',
                'promotions.apply',
                'test_drives.view',
                'test_drives.edit',
                'test_drives.delete',
                'test_drives.export',
                'warranties.view',
                'reviews.view',
                'live.leads.view',
                'live.leads.edit',
            ],
        ],
        'Nhân viên dịch vụ / CSKH' => [
            'legacy_role' => 'staff',
            'permissions' => [
                'dashboard.view',
                'customers.view',
                'tickets.view',
                'tickets.reply',
                'warranties.view',
                'services.view',
                'services.create',
                'services.edit',
                'service_records.view',
                'service_records.create',
                'reviews.view',
                'reviews.moderate',
                'reviews.reply',
            ],
        ],
        'Marketing' => [
            'legacy_role' => 'staff',
            'permissions' => [
                'dashboard.view',
                'news.view',
                'news.create',
                'news.edit',
                'news.delete',
                'news.publish',
                'news_categories.view',
                'news_categories.create',
                'news_categories.edit',
                'news_categories.delete',
                'promotions.view',
                'promotions.create',
                'promotions.edit',
                'promotions.delete',
                'promotions.publish',
                'promotions.apply',
                'reviews.view',
                'live.view',
                'live.create',
                'live.edit',
                'live.manage',
                'live.leads.view',
            ],
        ],
        'Kế toán' => [
            'legacy_role' => 'staff',
            'permissions' => [
                'dashboard.view',
                'orders.view',
                'quotes.view',
                'reports.view',
                'customers.view',
                'warranties.view',
                'services.view',
                'service_records.view',
            ],
        ],
    ],
];
